config/routes.rb
TeamStatusApp::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'users'}

  devise_scope :user do
    resources :users, :only => [:show]
  end

  resources :groups do
    get 'get_statuses', :to => 'groups#get_statuses'

    resources :statuses do
      put 'switch_tracking', :on => :member
    end

    resources :agendas

    put 'remove_member/:user_id', :to => 'groups#remove_member'
    get 'leave_group', :to => 'groups#leave_group'
  end

  root :to => 'home#index'

end

app/models/group.rb
class Group < ActiveRecord::Base

  attr_accessible :name, :owner_id
  validates_presence_of :name
  validates_uniqueness_of :name

  has_and_belongs_to_many :users
  has_many :statuses, :dependent => :destroy
  has_many :agendas, :dependent => :destroy
end

app/controllers/groups_controller.rb
require 'json'
require 'rails_autolink'

class GroupsController < ApplicationController

  def new
    @group = Group.new
    @possible_users_to_add = User.all(:conditions => ["id != ?", current_user.id])
  end

  def create
    @group = Group.new params[:group]
    @group.owner_id = current_user.id
    @group.users << current_user
    @group.users << User.find(params[:person]) if params[:person].present?

    if @group.save
      redirect_to @group
    else
      @possible_users_to_add = User.all(:conditions => ["id != ?", current_user.id]) # need to redo this; 'nil' otherwise
      render :new # just rendering view
    end
  end

  def edit
    @group = Group.find params[:id]
    @is_owner = true if @group.owner_id == current_user.id rescue nil
    @existing_member_ids = @group.users.map { |hash| hash[:id ] }
    @possible_users_to_add = User.all(:conditions => ["id not in (?)", @existing_member_ids])
  end

  def update
    @group = Group.find params[:id]
    @group.users << User.find(params[:person]) if params[:person].present?
    if @group.update_attributes params[:group]
      redirect_to @group
    else
      render :edit
    end
  end

  def show
    @group = Group.find params[:id]

    @members = @group.users
    @owner = User.find @group.owner_id rescue nil
    @is_owner = true if @group.owner_id == current_user.id rescue nil
    @is_member = true if @members.where(:id => current_user.id).present? rescue nil

    @agendas = []
    @members.each do |member|
      @agendas << member.agendas.where(:group_id => @group.id).first_or_create
    end

    page = params[:page] || 1
    per_page = 20
    @statuses = @group.statuses.paginate(:page => page, :per_page => per_page).all(:order => 'created_at DESC')
  end

  def remove_member
    member = User.find params[:user_id]
    group = Group.find params[:group_id] # not :id (see routes)
    member.agendas.where(:group_id => group.id).delete_all # remove associated agenda
    group.users.delete(member)

    output = {'status' => 'ok'}.to_json
    render json: output
  end

  def leave_group
    group = Group.find params[:group_id]
    current_user.agendas.where(:group_id => group.id).delete_all
    group.users.delete(current_user)
    redirect_to user_path(current_user)
  end

  def destroy
    group = Group.find params[:id]
    group.destroy
    redirect_to user_path(current_user)
  end

end

app/views/groups/_agendas.html.haml
.medium-6.large-4.columns
  .callout.panel.group-agendas
    .section-heading
      %h4 Today's Agenda
      %span.has-tip.tip-top.agenda-how-to-edit{"data-tooltip" => "", title: "Double-click on your own agenda to open the editable text box. The updated agenda is saved when you click on something else."} (How to edit?)
    %p.agenda-instructions

    - @agendas.each do |agenda|
      - if agenda.user == current_user
        - css_class = "individual-agenda-editable"
      - else
        - css_class = "invidual-agenda"
      .group-agenda-item
        .creator= agenda.user.full_name
        %div{:class => "#{css_class}", "data-group-id" => "#{@group.id}", "data-agenda-id" => "#{agenda.id}", "data-agenda-body" => "#{agenda.body}"}
          .content<
            - if agenda.body?
              = agenda.body
            - else
              (None entered yet.)
        - unless agenda == @agendas.last
          %hr/

app/views/groups/_details.html.haml
- if @group.errors.any?
  .alert-box.alert
    - @group.errors.full_messages.each do |msg|
      = msg

= form_for(@group, html: {id: 'group-details-form'}) do |f|
  %fieldset
    %legend Group Details
    .field
      = f.label :name
      = f.text_field :name
    .field
      = label_tag  :person, 'Add User to Group'
      = select_tag :person, options_from_collection_for_select(@possible_users_to_add, 'id', 'full_name'), :include_blank => true
    .actions
      = f.submit :class => 'button round'

  - if params[:id].present?
    .edit-group-delete-link
      = link_to 'Remove Group', @group, :method => :delete, :confirm => "Are you sure? All its associated data will be gone!"

app/views/groups/_members.html.haml
%span.group-role Admin
- if @owner.nil?
  %span.group-admin [Deleted User]
- else
  %span.group-admin= "#{@owner.full_name} (@#{@owner.username})"
- if @is_owner == true
  %small.group-admin-edit-link
    = link_to 'Add Member/Edit Group Name', edit_group_path(@group)
.row.clear
%span.group-role Members
.group-members-list
  %ul.inline-list.group-member
    - @members.each do |member|
      - if member != @owner # can't move this to line below without extra space/line when false
        %li
          = "#{member.full_name} (@#{member.username})"
          - if @is_owner == true
            %small
              %a.remove-from-group{"data-group-id" => "#{@group.id}", "data-member-id" => "#{member.id}"}= "Remove from Group"
          - elsif current_user == member
            %small
              .group-member-leave-group-link
                = link_to 'Leave Group', group_leave_group_path(@group), :confirm => "Are you sure you'd like to leave this group?"
          - else
            %small{:style => "visibility: hidden;"} Placeholder



/ - else
/   .group-member-leave-group-link
/     = link_to "Leave Group", "#", "data-group-id" => "#{@group.id}", "data-member-id" => "#{current_user.id}"

app/views/groups/_statuses.html.haml
.medium-6.large-8.columns

  %h3 What is everyone up to?

  = form_for([@group, @group.statuses.build], html: {id: 'add-status-form'}) do |f|
    %fieldset
      %legend Share your latest status
      .field
        = f.label :body, 'Current status'
        %a{"data-reveal-id" => "myModal", href: "#", class: "example-status"} (Examples)
        #myModal.reveal-modal.example-status{"data-reveal" => ""}
          %h3 What should my statuses look like?
          %p There are basically two types of statuses:
          %ol
            %li
              %strong What you're working on
              %br/
              %em e.g.
              %ul
                %li Working on newsletter design
                %li Client meeting
            %li
              %strong What you'd like to say to one or all of your group members
              %br/
              %em e.g.
              %ul
                %li @all Anyone have good examples of car insurance websites to share?
                %li @foobar Just came across this site and thought you might want to check it out: http://...
          %p All usernames can be found under the members section.
          %a.close-reveal-modal ×
        = f.text_area :body, :size => '50x3'
      .field
        = f.label :tracking, 'Enable time-tracking for this item?'
        = f.check_box :tracking
        %span.has-tip.tip-right.example-time-tracking{"data-tooltip" => "", title: "You might want to enable time-tracking if your status is 'Working on newsletter design', but not if it's '@all I have pizza in the kitchen!'"} (What's this?)
      .field
        = hidden_field_tag :group_id, @group.id
      .actions
        = f.submit :class => 'button small'

  .group-status-list
    - @statuses.each do |message|
      - if message.at_user == current_user.username || message.at_user == "all"
        - css_class = "callout panel group-status-mention"
      - else
        - css_class = "panel"
      %div{:class => "#{css_class}"}
        .group-status-list-item
          %span.creator
            - if message.user.present?
              = "#{message.user.full_name} (@#{message.user.username})"
            - else
              = "[Deleted User]"
            \|
          %span.time= time_ago_in_words(message.created_at) + ' ago'
          - if message.tracking?
            %span.tracking-label.in-progress= "in progress"
          - if message.tracked? && !(message.tracking?)
            %span.tracking-label.done= "done"
          .content
            = auto_link(message.body, :html => {:target => '_blank'}) do |text|
              - truncate(text)
          - if message.user_id == current_user.id
            - if message.tracking?
              = link_to "Finish Tracking | ", "#", :class => "update-status-tracking-link", "data-group-id" => "#{@group.id}", "data-status-id" => "#{message.id}"
            = link_to "Delete Status", "#", :class => "delete-status-link", "data-group-id" => "#{@group.id}", "data-status-id" => "#{message.id}"

app/views/groups/edit.html.haml
.container
  .row.clear
  .row
    .small-9.small-centered.medium-centered.large-centered.columns
      - if user_signed_in?
        - if @is_owner == true
          %h2 Update Group
          = render 'details'
        - else
          %p This is not the group you're looking for...
      - else
        %p Please sign up or sign in.

app/views/groups/new.html.haml
.container
  .row.clear
  .row
    .small-9.small-centered.medium-centered.large-centered.columns
      - if user_signed_in?
        %h2 Create a Group
        = render 'details'
      - else
        %p Please sign up or sign in.

app/views/groups/show.html.haml
/ :javascript
/   setTimeout(function(){ location = '' }, 300000)

- if user_signed_in?
  - if @is_member == true
    .row
      %h2= @group.name.titleize
      .panel
        = render 'members'
    .row
      .large-12.columns
        .groups-statuses-section
          = render 'statuses'
        .groups-agendas-section
          = render 'agendas'
    .row
      .large-12.columns
        = will_paginate @statuses, renderer: FoundationPagination::Rails
    .row.clear
  - else
    %p This is not the group you're looking for...
- else
  %p Please sign up or sign in.