config/routes.rb
TeamStatusApp::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'users'}

  devise_scope :user do
    resources :users, :only => [:show]
  end

  resources :groups do
    get 'get_statuses', :to => 'groups#get_statuses'

    resources :statuses do
      put 'switch_tracking', :on => :member
    end

    resources :agendas

    put 'remove_member/:user_id', :to => 'groups#remove_member'
    get 'leave_group', :to => 'groups#leave_group'
  end

  root :to => 'home#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title TeamStatusApp
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application'
    = yield(:javascripts)
    = csrf_meta_tags

  %body

    - if !user_signed_in?
      %nav.top-bar{"data-topbar" => ""}
        %ul.title-area
          %li.name
            %h1.home-nav= link_to 'TeamStatusApp', root_path
          / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
          %li.toggle-topbar.menu-icon
            %a{href: "#"}
        %section.top-bar-section
          / Left Nav Section
          %ul.left
            %li= link_to 'Sign Up', new_user_registration_path
            %li= link_to 'Sign In', new_user_session_path
      %section.main-section
        = render 'layouts/messages'
        = yield
    - else
      .off-canvas-wrap{"data-offcanvas" => ""}
        .inner-wrap
          %nav.tab-bar
            %section.left-small
              %a.left-off-canvas-toggle.menu-icon{href: "#"}
                %span
            %section.middle.tab-bar-section
              %h1.title TeamStatusApp
          %aside.left-off-canvas-menu
            %ul.off-canvas-list
              %li
                %label Your Groups
              - current_user.groups.each do |group|
                %li
                  - if group.owner_id == current_user.id
                    = link_to "#{group.name} [Admin]", group_path(group)
                  - else
                    = link_to group.name, group_path(group) if group.valid?
              %li
                %label More...
              %li= link_to 'Go to Dashboard', user_path(current_user)
              %li= link_to 'Start a New Group', new_group_path
              %li
                %label Your Account
              %li= link_to 'Settings', edit_user_registration_path(current_user)
              %li= link_to 'Log Out', destroy_user_session_path, :method => :delete
          %section.main-section
            = render 'layouts/messages'
            = yield
            %a.exit-off-canvas

app/views/layouts/foundation_application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>